# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2023.4.4.dev0+g434be70.d20230625'
__version_tuple__ = version_tuple = (2023, 4, 4, 'dev0', 'g434be70.d20230625')
