name: "install-robotpy-build"
description: "Installs robotpy-build"
inputs:
  python:
    description: "python executable"
    required: false
    default: python
  working_directory:
    required: true
    type: string
runs:
  using: "node12"
  main: dist/index.js
