name: "install-robotpy-build"
description: "Installs robotpy-build"
inputs:
  python:
    description: "python executable"
    required: false
    default: python

runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      ${{ inputs.python }} -m pip install robotpy-build