name: "validate-sphinx"
description: "Validate sphinx documentation"
inputs:
  docsdir:
    description: "Documentation directory"
    required: false
    default: docs
  sphinxopts:
    description: "Options to pass to sphinx"
    required: false
    default: "-W --keep-going"

  working_directory:
    description: "working directory"
    required: true
    type: string

defaults:
  run:
    working-directory: ${{ inputs.working_directory }}

runs:
  using: "composite"
  steps:
  - name: Install documentation dependencies
    shell: bash
    run: pip --disable-pip-version-check install -r ${{ inputs.docsdir }}/requirements.txt
  - name: Validate sphinx documentation
    shell: bash
    run: cd ${{ inputs.docsdir }} && make clean html SPHINXOPTS="${{ inputs.sphinxopts }}"
