name: "install-build-deps"
description: "Install build dependencies"
inputs:
  python:
    description: "python executable"
    required: false
    default: python
  wheeldir:
    description: "Wheel directory"
    required: false
    default: linux_x86_64
  working_directory:
    required: true
    type: string
runs:
  using: "composite"
  steps:
  - shell: bash
    working-directory: ${{ inputs.working_directory }}
    run: |
      ${{ inputs.python }} -m robotpy_build build-dep --install \
        --find-links https://www.tortall.net/~robotpy/wheels/2022/${{ inputs.wheeldir }}
