---
name: go

on:
  pull_request:
  push:
    # tags:
    # - '*'

jobs:
  check:
    runs-ons: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: psd/black@stable

  wpiutil:
    # needs: [build]
    uses: ./.github/workflows/package-ci.yml
    with:
      enable_raspbian: false
      enable_sphinx_check: false
      working-directory: "wpiutil"